version: "3"

networks:
  curlys-net:

services:
  postgres:
    container_name: curlys-postgres
    image: postgres:latest
    ports:
      - 50040:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=curlys
      - POSTGRES_USER=curlys
      - POSTGRES_PASSWORD=b9ysCVHT8gcpdUEWSSHH3n49
    restart: always
    networks:
      - curlys-net

  redis:
    container_name: curlys-redis
    image: redis:latest
    ports:
      - 60039:6379
    volumes:
      - ./data/redis:/data
    command: >
      --requirepass RE3nKn3kPSu3qPua
    restart: always
    networks:
      - curlys-net
