version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 50040:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=curlys
      - POSTGRES_USER=curlys
      - POSTGRES_PASSWORD=b9ysCVHT8gcpdUEWSSHH3n49
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 60039:6379
    volumes:
      - ./database/cache:/data
    command: >
      --requirepass RE3nKn3kPSu3qPua
    restart: unless-stopped
